os:
  - linux
services:
  - docker
language: java
node_js:
  - "6.9.1"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=6.9.1
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - ./mvnw clean
  - ./mvnw test
  - gulp test
  - ./mvnw package -Pprod -DskipTests
notifications:
  slack:
    secure: 0VJD7zhFqWdZB87jO1FznfyXzMQdc5SDutnx6TWWMDASz9+KGBm1JjIS0XNFaHbFhR+mKFc2ydILi+Ksb1v0cl56munr7eFwth6E3fwyK/Q0mYiyJa13AcQirLgOTpa45Mh867MjvoQkByeqGOX78iOdk+AgpsfxFhnvKYSCZc+uxLKp9Kc52XF+51VAXOQOIN5GExW8ZuiaP0pWyF9lGQMCI8drJRpWniobrIWpOvjuaeJUVJTt4W22BFEBpnJ9BuliMR31i2cWt0wW9kk4WMCgMHSqEIPUhjxpTP7RlctUnS8fSl1Q2jaDHmpmmEolinZtHOa9xOgf7R7b8o0lythkwYj8KWb5eGXLEJv0nVJOFFuCQgNGRglTqgoeYtET3zHPeFBqngjM06AbnJU0i6AM1K6Ag0LB5oyTXPC32mR4fzgSqxkFopqK7o7e84XBJdv8HskQkMUrsSWcanRg1WOmG8nFyKQ4ba9XKWXZ12yaihDxszYh+Af3a9qTK8yLu3nQdZvxeVtiPgHbIKIKKUWXwqxyJrVFZLxZg3Crc70vUnJEkbRnQIHCJ0i8aCjlLDlLvFIrtosen1l3JB2O1xDhje5Vpd+TZDXGNuVxTQQCSbY3eJ7iRPYIYF1PCjq9vGXHHzDQdA18EKVgMI76+jFWkDI6/4sot1BuvF8obBk=
    email: false

branches:
  only:
  - master
